obs_space:  [[36, [1, 12], [1, 6], [1, 4], [1, 14]], [36, [1, 12], [1, 6], [1, 4], [1, 14]]]
share_obs_space:  [[44, [1, 15], [1, 9], [1, 4], [1, 16]], [44, [1, 15], [1, 9], [1, 4], [1, 16]]]
act_space:  [Discrete(7), Discrete(7)]
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 22707 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-gd8fn8w5/'
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 16091 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-myn2357d/'
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 17250 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-645uz_09/'
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 23671 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-gzqinqr_/'
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 18161 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-r8ydh0fs/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 17796 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-blvurs71/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 19195 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-fce6mjqe/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 23781 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-7sestv2p/'
Starting up...
Starting up...
Starting up...
Starting up...
Starting up...
Starting up...
Starting up...
Starting up...
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Listening on: 127.0.0.1:17796
Listening on: 127.0.0.1:19195
Startup Phase 3 complete. Ready for commands.
Startup Phase 3 complete. Ready for commands.
ConnectHandler: Request from 127.0.0.1:53846 accepted
ReadyHandler: 127.0.0.1:53846 ready
ConnectHandler: Request from 127.0.0.1:47794 accepted
ReadyHandler: 127.0.0.1:47794 ready
Process Process-4:
Process Process-7:
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 388, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 345, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 388, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 345, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
CloseHandler: 127.0.0.1:47794 disconnected
CloseHandler: 127.0.0.1:53846 disconnected
Listening on: 127.0.0.1:16091
Startup Phase 3 complete. Ready for commands.
Listening on: 127.0.0.1:18161
Listening on: 127.0.0.1:23671
Startup Phase 3 complete. Ready for commands.
Listening on: 127.0.0.1:22707
Startup Phase 3 complete. Ready for commands.
Listening on: 127.0.0.1:17250
Startup Phase 3 complete. Ready for commands.
Startup Phase 3 complete. Ready for commands.
Listening on: 127.0.0.1:23781
Startup Phase 3 complete. Ready for commands.
ConnectHandler: Request from 127.0.0.1:55734 accepted
ReadyHandler: 127.0.0.1:55734 ready
ConnectHandler: Request from 127.0.0.1:46466 accepted
ReadyHandler: 127.0.0.1:46466 ready
ConnectHandler: Request from 127.0.0.1:60964 accepted
ReadyHandler: 127.0.0.1:60964 ready
ConnectHandler: Request from 127.0.0.1:39532 accepted
ReadyHandler: 127.0.0.1:39532 ready
ConnectHandler: Request from 127.0.0.1:44572 accepted
ReadyHandler: 127.0.0.1:44572 ready
ConnectHandler: Request from 127.0.0.1:60996 accepted
ReadyHandler: 127.0.0.1:60996 ready
Process Process-6:
Process Process-8:
Process Process-5:
Process Process-3:
Process Process-2:
Process Process-9:
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 388, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 345, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 388, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 345, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
CloseHandler: 127.0.0.1:55734 disconnected
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 388, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 345, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 388, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 345, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 388, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 345, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 388, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 345, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
CloseHandler: 127.0.0.1:44572 disconnected
CloseHandler: 127.0.0.1:46466 disconnected
CloseHandler: 127.0.0.1:60964 disconnected
CloseHandler: 127.0.0.1:39532 disconnected
CloseHandler: 127.0.0.1:60996 disconnected
Traceback (most recent call last):
  File "../train/train_smac.py", line 262, in <module>
    main(sys.argv[1:])
  File "../train/train_smac.py", line 247, in main
    runner.run()
  File "/content/drive/MyDrive/on-policy/onpolicy/runner/shared/smac_runner.py", line 17, in run
    self.warmup()
  File "/content/drive/MyDrive/on-policy/onpolicy/runner/shared/smac_runner.py", line 100, in warmup
    obs, share_obs, available_actions = self.envs.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 377, in reset
    results = [remote.recv() for remote in self.remotes]
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 377, in <listcomp>
    results = [remote.recv() for remote in self.remotes]
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
