obs_space:  [[36, [1, 12], [1, 6], [1, 4], [1, 14]], [36, [1, 12], [1, 6], [1, 4], [1, 14]]]
share_obs_space:  [[44, [1, 15], [1, 9], [1, 4], [1, 16]], [44, [1, 15], [1, 9], [1, 4], [1, 16]]]
act_space:  [Discrete(7), Discrete(7)]
2m_vs_1z
    file: 'SMAC_Maps/2m_vs_1z.SC2Map'
    players: 2, score_index: -1, score_multiplier: 1
    step_mul: 8, game_steps_per_episode: 0
2m_vs_1z
    file: 'SMAC_Maps/2m_vs_1z.SC2Map'
    players: 2, score_index: -1, score_multiplier: 1
    step_mul: 8, game_steps_per_episode: 0
2m_vs_1z
    file: 'SMAC_Maps/2m_vs_1z.SC2Map'
    players: 2, score_index: -1, score_multiplier: 1
    step_mul: 8, game_steps_per_episode: 0
2m_vs_1z
    file: 'SMAC_Maps/2m_vs_1z.SC2Map'
    players: 2, score_index: -1, score_multiplier: 1
    step_mul: 8, game_steps_per_episode: 0
2m_vs_1z
    file: 'SMAC_Maps/2m_vs_1z.SC2Map'
    players: 2, score_index: -1, score_multiplier: 1
    step_mul: 8, game_steps_per_episode: 0
2m_vs_1z
    file: 'SMAC_Maps/2m_vs_1z.SC2Map'
    players: 2, score_index: -1, score_multiplier: 1
    step_mul: 8, game_steps_per_episode: 0
2m_vs_1z
    file: 'SMAC_Maps/2m_vs_1z.SC2Map'
    players: 2, score_index: -1, score_multiplier: 1
    step_mul: 8, game_steps_per_episode: 0
2m_vs_1z
    file: 'SMAC_Maps/2m_vs_1z.SC2Map'
    players: 2, score_index: -1, score_multiplier: 1
    step_mul: 8, game_steps_per_episode: 0
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 19806 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-hx2395hy/'
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 21570 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-7iiyjr3n/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 23044 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-fud3_r75/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 23861 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-o0fge9j3/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 22875 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-7f18lcec/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 18592 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-j5fw0pb3/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 24085 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-xsyogtzl/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 16272 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-9_6e552t/'
Starting up...
Starting up...
Starting up...
Starting up...
Starting up...
Starting up...
Starting up...
Starting up...
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Listening on: 127.0.0.1:23861
Startup Phase 3 complete. Ready for commands.
Listening on: 127.0.0.1:23044
Startup Phase 3 complete. Ready for commands.
ConnectHandler: Request from 127.0.0.1:48742 accepted
ReadyHandler: 127.0.0.1:48742 ready
ConnectHandler: Request from 127.0.0.1:39812 accepted
ReadyHandler: 127.0.0.1:39812 ready
Process Process-3:
Process Process-5:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 389, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 346, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 389, in reset
    self._launch()
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 346, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
CloseHandler: 127.0.0.1:48742 disconnected
CloseHandler: 127.0.0.1:39812 disconnected
Listening on: 127.0.0.1:19806
Startup Phase 3 complete. Ready for commands.
Listening on: 127.0.0.1:24085
Startup Phase 3 complete. Ready for commands.
Listening on: 127.0.0.1:22875
Listening on: 127.0.0.1:21570
Startup Phase 3 complete. Ready for commands.
Startup Phase 3 complete. Ready for commands.
Listening on: 127.0.0.1:16272
Startup Phase 3 complete. Ready for commands.
Listening on: 127.0.0.1:18592
Startup Phase 3 complete. Ready for commands.
ConnectHandler: Request from 127.0.0.1:33688 accepted
ReadyHandler: 127.0.0.1:33688 ready
ConnectHandler: Request from 127.0.0.1:45104 accepted
ReadyHandler: 127.0.0.1:45104 ready
ConnectHandler: Request from 127.0.0.1:49100 accepted
ReadyHandler: 127.0.0.1:49100 ready
Process Process-8:
Process Process-2:
Process Process-4:
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 389, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 346, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 389, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 346, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
ConnectHandler: Request from 127.0.0.1:56080 accepted
ReadyHandler: 127.0.0.1:56080 ready
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 389, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 346, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
Process Process-9:
CloseHandler: 127.0.0.1:33688 disconnected
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 389, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 346, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
CloseHandler: 127.0.0.1:45104 disconnected
ConnectHandler: Request from 127.0.0.1:48836 accepted
ReadyHandler: 127.0.0.1:48836 ready
CloseHandler: 127.0.0.1:49100 disconnected
Process Process-6:
CloseHandler: 127.0.0.1:56080 disconnected
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 389, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 346, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
CloseHandler: 127.0.0.1:48836 disconnected
ConnectHandler: Request from 127.0.0.1:38570 accepted
ReadyHandler: 127.0.0.1:38570 ready
Process Process-7:
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 389, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 346, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
CloseHandler: 127.0.0.1:38570 disconnected
Traceback (most recent call last):
  File "../train/train_smac.py", line 262, in <module>
    main(sys.argv[1:])
  File "../train/train_smac.py", line 247, in main
    runner.run()
  File "/content/drive/MyDrive/on-policy/onpolicy/runner/shared/smac_runner.py", line 17, in run
    self.warmup()
  File "/content/drive/MyDrive/on-policy/onpolicy/runner/shared/smac_runner.py", line 100, in warmup
    obs, share_obs, available_actions = self.envs.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 377, in reset
    results = [remote.recv() for remote in self.remotes]
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 377, in <listcomp>
    results = [remote.recv() for remote in self.remotes]
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
