obs_space:  [[36, [1, 12], [1, 6], [1, 4], [1, 14]], [36, [1, 12], [1, 6], [1, 4], [1, 14]]]
share_obs_space:  [[44, [1, 15], [1, 9], [1, 4], [1, 16]], [44, [1, 15], [1, 9], [1, 4], [1, 16]]]
act_space:  [Discrete(7), Discrete(7)]
2m_vs_1z
2m_vs_1z
    file: 'SMAC_Maps/2m_vs_1z.SC2Map'
    players: 2, score_index: -1, score_multiplier: 1
    step_mul: 8, game_steps_per_episode: 0
2m_vs_1z
2m_vs_1z
    file: 'SMAC_Maps/2m_vs_1z.SC2Map'
    players: 2, score_index: -1, score_multiplier: 1
    step_mul: 8, game_steps_per_episode: 0
2m_vs_1z
2m_vs_1z
    file: 'SMAC_Maps/2m_vs_1z.SC2Map'
    players: 2, score_index: -1, score_multiplier: 1
    step_mul: 8, game_steps_per_episode: 0
2m_vs_1z
2m_vs_1z
    file: 'SMAC_Maps/2m_vs_1z.SC2Map'
    players: 2, score_index: -1, score_multiplier: 1
    step_mul: 8, game_steps_per_episode: 0
2m_vs_1z
2m_vs_1z
    file: 'SMAC_Maps/2m_vs_1z.SC2Map'
    players: 2, score_index: -1, score_multiplier: 1
    step_mul: 8, game_steps_per_episode: 0
2m_vs_1z
2m_vs_1z
    file: 'SMAC_Maps/2m_vs_1z.SC2Map'
    players: 2, score_index: -1, score_multiplier: 1
    step_mul: 8, game_steps_per_episode: 0
2m_vs_1z
2m_vs_1z
    file: 'SMAC_Maps/2m_vs_1z.SC2Map'
    players: 2, score_index: -1, score_multiplier: 1
    step_mul: 8, game_steps_per_episode: 0
2m_vs_1z
2m_vs_1z
    file: 'SMAC_Maps/2m_vs_1z.SC2Map'
    players: 2, score_index: -1, score_multiplier: 1
    step_mul: 8, game_steps_per_episode: 0
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 16253 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-94zszrx9/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 18651 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-4n8exfkt/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 22296 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-8v9z3s3o/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 19354 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-0z4zajni/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 19942 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-ziqtsi7a/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 15876 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-uc00az5t/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 24727 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-e35z_qsn/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 20516 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-vv101lnv/'
Starting up...
Starting up...
Starting up...
Starting up...
Starting up...
Starting up...
Starting up...
Starting up...
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Listening on: 127.0.0.1:19942
Listening on: 127.0.0.1:15876
ConnectHandler: Request from 127.0.0.1:32850 accepted
ReadyHandler: 127.0.0.1:32850 ready
ConnectHandler: Request from 127.0.0.1:44324 accepted
ReadyHandler: 127.0.0.1:44324 ready
Startup Phase 3 complete. Ready for commands.
Startup Phase 3 complete. Ready for commands.
Process Process-2:
Process Process-4:
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 390, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 347, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 390, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 347, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
CloseHandler: 127.0.0.1:32850 disconnected
CloseHandler: 127.0.0.1:44324 disconnected
Listening on: 127.0.0.1:19354
Startup Phase 3 complete. Ready for commands.
ConnectHandler: Request from 127.0.0.1:60054 accepted
ReadyHandler: 127.0.0.1:60054 ready
Process Process-3:
Listening on: 127.0.0.1:24727
Listening on: 127.0.0.1:20516
Listening on: 127.0.0.1:22296
Startup Phase 3 complete. Ready for commands.
Startup Phase 3 complete. Ready for commands.
Startup Phase 3 complete. Ready for commands.
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 390, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 347, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
CloseHandler: 127.0.0.1:60054 disconnected
Listening on: 127.0.0.1:18651
Startup Phase 3 complete. Ready for commands.
Listening on: 127.0.0.1:16253
Startup Phase 3 complete. Ready for commands.
ConnectHandler: Request from 127.0.0.1:43040 accepted
ReadyHandler: 127.0.0.1:43040 ready
Process Process-9:
ConnectHandler: Request from 127.0.0.1:51898 accepted
ReadyHandler: 127.0.0.1:51898 ready
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 390, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 347, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
ConnectHandler: Request from 127.0.0.1:57906 accepted
ReadyHandler: 127.0.0.1:57906 ready
ConnectHandler: Request from 127.0.0.1:54882 accepted
ReadyHandler: 127.0.0.1:54882 ready
Process Process-6:
CloseHandler: 127.0.0.1:43040 disconnected
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 390, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 347, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
ConnectHandler: Request from 127.0.0.1:44934 accepted
ReadyHandler: 127.0.0.1:44934 ready
Process Process-5:
Process Process-8:
Process Process-7:
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 390, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 347, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
CloseHandler: 127.0.0.1:51898 disconnected
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 390, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 347, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 390, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 347, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
CloseHandler: 127.0.0.1:57906 disconnected
CloseHandler: 127.0.0.1:54882 disconnected
CloseHandler: 127.0.0.1:44934 disconnected
Traceback (most recent call last):
  File "../train/train_smac.py", line 262, in <module>
    main(sys.argv[1:])
  File "../train/train_smac.py", line 247, in main
    runner.run()
  File "/content/drive/MyDrive/on-policy/onpolicy/runner/shared/smac_runner.py", line 17, in run
    self.warmup()
  File "/content/drive/MyDrive/on-policy/onpolicy/runner/shared/smac_runner.py", line 100, in warmup
    obs, share_obs, available_actions = self.envs.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 377, in reset
    results = [remote.recv() for remote in self.remotes]
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 377, in <listcomp>
    results = [remote.recv() for remote in self.remotes]
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
