<onpolicy.envs.starcraft2.StarCraft2_Env.StarCraft2Env object at 0x78c19e04b160>
<onpolicy.envs.starcraft2.StarCraft2_Env.StarCraft2Env object at 0x78c19e04b160>
<onpolicy.envs.starcraft2.StarCraft2_Env.StarCraft2Env object at 0x78c19e04b160>
<onpolicy.envs.starcraft2.StarCraft2_Env.StarCraft2Env object at 0x78c19e04b160>
<onpolicy.envs.starcraft2.StarCraft2_Env.StarCraft2Env object at 0x78c19e04b160>
<onpolicy.envs.starcraft2.StarCraft2_Env.StarCraft2Env object at 0x78c19e04b160>
<onpolicy.envs.starcraft2.StarCraft2_Env.StarCraft2Env object at 0x78c19e04b160>
<onpolicy.envs.starcraft2.StarCraft2_Env.StarCraft2Env object at 0x78c19e04b160>
obs_space:  [[36, [1, 12], [1, 6], [1, 4], [1, 14]], [36, [1, 12], [1, 6], [1, 4], [1, 14]]]
share_obs_space:  [[44, [1, 15], [1, 9], [1, 4], [1, 16]], [44, [1, 15], [1, 9], [1, 4], [1, 16]]]
act_space:  [Discrete(7), Discrete(7)]
Process Process-2:
Process Process-4:
Process Process-3:
Process Process-5:
Process Process-6:
Process Process-7:
Process Process-8:
Process Process-9:
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 317, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 388, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 332, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/__init__.py", line 40, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 179, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 63, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 112, in __init__
    self.version = self._get_version(version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 220, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 94, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/root/StarCraftII/Versions'
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 317, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 388, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 332, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/__init__.py", line 40, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 179, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 63, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 112, in __init__
    self.version = self._get_version(version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 220, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 94, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/root/StarCraftII/Versions'
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 317, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 388, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 332, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/__init__.py", line 40, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 179, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 63, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 112, in __init__
    self.version = self._get_version(version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 220, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 94, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/root/StarCraftII/Versions'
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 317, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 388, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 332, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/__init__.py", line 40, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 179, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 63, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 112, in __init__
    self.version = self._get_version(version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 220, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 94, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/root/StarCraftII/Versions'
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 317, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 388, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 332, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/__init__.py", line 40, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 179, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 63, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 112, in __init__
    self.version = self._get_version(version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 220, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 94, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/root/StarCraftII/Versions'
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 317, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 388, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 332, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/__init__.py", line 40, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 179, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 63, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 112, in __init__
    self.version = self._get_version(version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 220, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 94, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/root/StarCraftII/Versions'
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 317, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 388, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 332, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/__init__.py", line 40, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 179, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 63, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 112, in __init__
    self.version = self._get_version(version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 220, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 94, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/root/StarCraftII/Versions'
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 317, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 388, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 332, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/__init__.py", line 40, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 179, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 63, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 112, in __init__
    self.version = self._get_version(version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 220, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 94, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/root/StarCraftII/Versions'
Traceback (most recent call last):
  File "../train/train_smac.py", line 261, in <module>
    main(sys.argv[1:])
  File "../train/train_smac.py", line 246, in main
    runner.run()
  File "/content/drive/MyDrive/on-policy/onpolicy/runner/shared/smac_runner.py", line 17, in run
    self.warmup()
  File "/content/drive/MyDrive/on-policy/onpolicy/runner/shared/smac_runner.py", line 100, in warmup
    obs, share_obs, available_actions = self.envs.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 378, in reset
    results = [remote.recv() for remote in self.remotes]
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 378, in <listcomp>
    results = [remote.recv() for remote in self.remotes]
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
