obs_space:  [[36, [1, 12], [1, 6], [1, 4], [1, 14]], [36, [1, 12], [1, 6], [1, 4], [1, 14]]]
share_obs_space:  [[44, [1, 15], [1, 9], [1, 4], [1, 16]], [44, [1, 15], [1, 9], [1, 4], [1, 16]]]
act_space:  [Discrete(7), Discrete(7)]
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 19836 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-8pebaw7p/'
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 16904 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-b2jl5k7y/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 15613 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-k3b084cv/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 15313 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-15h247y2/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 18939 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-u_u02bjn/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 24516 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-l1nybten/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 16657 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-uz5w4gll/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 21909 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-m6xizdww/'
Starting up...
Starting up...
Starting up...
Starting up...
Starting up...
Starting up...
Starting up...
Starting up...
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Listening on: 127.0.0.1:18939
Startup Phase 3 complete. Ready for commands.
ConnectHandler: Request from 127.0.0.1:50190 accepted
ReadyHandler: 127.0.0.1:50190 ready
Process Process-9:
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 388, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 345, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
Listening on: 127.0.0.1:15313
CloseHandler: 127.0.0.1:50190 disconnected
Startup Phase 3 complete. Ready for commands.
ConnectHandler: Request from 127.0.0.1:38820 accepted
ReadyHandler: 127.0.0.1:38820 ready
Process Process-8:
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 388, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 345, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
CloseHandler: 127.0.0.1:38820 disconnected
Listening on: 127.0.0.1:16657
Startup Phase 3 complete. Ready for commands.
Listening on: 127.0.0.1:19836
Startup Phase 3 complete. Ready for commands.
Listening on: 127.0.0.1:16904
Startup Phase 3 complete. Ready for commands.
Listening on: 127.0.0.1:21909
Startup Phase 3 complete. Ready for commands.
Listening on: 127.0.0.1:15613
Listening on: 127.0.0.1:24516
Startup Phase 3 complete. Ready for commands.
Startup Phase 3 complete. Ready for commands.
ConnectHandler: Request from 127.0.0.1:44860 accepted
ReadyHandler: 127.0.0.1:44860 ready
Process Process-5:
ConnectHandler: Request from 127.0.0.1:37714 accepted
ReadyHandler: 127.0.0.1:37714 ready
Traceback (most recent call last):
ConnectHandler: Request from 127.0.0.1:34584 accepted
ReadyHandler: 127.0.0.1:34584 ready
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 388, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 345, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
Process Process-7:
Process Process-2:
CloseHandler: 127.0.0.1:44860 disconnected
ConnectHandler: Request from 127.0.0.1:41176 accepted
ReadyHandler: 127.0.0.1:41176 ready
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 388, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 345, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
ConnectHandler: Request from 127.0.0.1:46966 accepted
ReadyHandler: 127.0.0.1:46966 ready
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 388, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 345, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
ConnectHandler: Request from 127.0.0.1:33868 accepted
ReadyHandler: 127.0.0.1:33868 ready
Process Process-3:
Process Process-6:
Process Process-4:
CloseHandler: 127.0.0.1:37714 disconnected
CloseHandler: 127.0.0.1:34584 disconnected
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 388, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 345, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 388, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 345, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 388, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 345, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
CloseHandler: 127.0.0.1:33868 disconnected
CloseHandler: 127.0.0.1:41176 disconnected
CloseHandler: 127.0.0.1:46966 disconnected
Traceback (most recent call last):
  File "../train/train_smac.py", line 262, in <module>
    main(sys.argv[1:])
  File "../train/train_smac.py", line 247, in main
    runner.run()
  File "/content/drive/MyDrive/on-policy/onpolicy/runner/shared/smac_runner.py", line 17, in run
    self.warmup()
  File "/content/drive/MyDrive/on-policy/onpolicy/runner/shared/smac_runner.py", line 100, in warmup
    obs, share_obs, available_actions = self.envs.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 377, in reset
    results = [remote.recv() for remote in self.remotes]
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 377, in <listcomp>
    results = [remote.recv() for remote in self.remotes]
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
