obs_space:  [[36, [1, 12], [1, 6], [1, 4], [1, 14]], [36, [1, 12], [1, 6], [1, 4], [1, 14]]]
share_obs_space:  [[44, [1, 15], [1, 9], [1, 4], [1, 16]], [44, [1, 15], [1, 9], [1, 4], [1, 16]]]
act_space:  [Discrete(7), Discrete(7)]
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 24331 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-4zys3mjk/'
Version: B75689 (SC2.4.10)
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 15770 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-bzbthby_/'
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 23118 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-4fo7omxp/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 20527 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-l4616vyu/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 18727 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-9_lynsmx/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 22378 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-2m2yyjm7/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 22929 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-2tnsajo_/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/content/drive/MyDrive/on-policy/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 15163 -dataDir /content/drive/MyDrive/on-policy/StarCraftII/ -tempDir /tmp/sc-1o92c6iz/'
Starting up...
Starting up...
Starting up...
Starting up...
Starting up...
Starting up...
Starting up...
Starting up...
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Listening on: 127.0.0.1:24331
Startup Phase 3 complete. Ready for commands.
Listening on: 127.0.0.1:22929
Startup Phase 3 complete. Ready for commands.
Listening on: 127.0.0.1:15163
Startup Phase 3 complete. Ready for commands.
ConnectHandler: Request from 127.0.0.1:41432 accepted
ReadyHandler: 127.0.0.1:41432 ready
/content/drive/MyDrive/on-policy/StarCraftII/SMAC_Maps/2m_vs_1z.SC2Map
Process Process-2:
ConnectHandler: Request from 127.0.0.1:54060 accepted
ReadyHandler: 127.0.0.1:54060 ready
ConnectHandler: Request from 127.0.0.1:57094 accepted
ReadyHandler: 127.0.0.1:57094 ready
/content/drive/MyDrive/on-policy/StarCraftII/SMAC_Maps/2m_vs_1z.SC2Map
Traceback (most recent call last):
Process Process-6:
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 391, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 348, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
/content/drive/MyDrive/on-policy/StarCraftII/SMAC_Maps/2m_vs_1z.SC2Map
Process Process-7:
CloseHandler: 127.0.0.1:41432 disconnected
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 391, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 348, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 391, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 348, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
CloseHandler: 127.0.0.1:57094 disconnected
CloseHandler: 127.0.0.1:54060 disconnected
Listening on: 127.0.0.1:20527
Startup Phase 3 complete. Ready for commands.
Deferred error: 536936448 (0x20010000)
Deferred error details: Bad profiling data. TimeMS: 9955685.000000 Conversion: 1.000000e-03
Listening on: 127.0.0.1:22378
Startup Phase 3 complete. Ready for commands.
Listening on: 127.0.0.1:23118
Listening on: 127.0.0.1:18727
Startup Phase 3 complete. Ready for commands.
Startup Phase 3 complete. Ready for commands.
Listening on: 127.0.0.1:15770
Startup Phase 3 complete. Ready for commands.
ConnectHandler: Request from 127.0.0.1:35666 accepted
ReadyHandler: 127.0.0.1:35666 ready
ConnectHandler: Request from 127.0.0.1:46288 accepted
ReadyHandler: 127.0.0.1:46288 ready
ConnectHandler: Request from 127.0.0.1:40056 accepted
ReadyHandler: 127.0.0.1:40056 ready
ConnectHandler: Request from 127.0.0.1:35620 accepted
ReadyHandler: 127.0.0.1:35620 ready
/content/drive/MyDrive/on-policy/StarCraftII/SMAC_Maps/2m_vs_1z.SC2Map
ConnectHandler: Request from 127.0.0.1:59260 accepted
ReadyHandler: 127.0.0.1:59260 ready
/content/drive/MyDrive/on-policy/StarCraftII/SMAC_Maps/2m_vs_1z.SC2Map
Process Process-9:
/content/drive/MyDrive/on-policy/StarCraftII/SMAC_Maps/2m_vs_1z.SC2Map
Process Process-4:
Process Process-8:
/content/drive/MyDrive/on-policy/StarCraftII/SMAC_Maps/2m_vs_1z.SC2Map
Process Process-5:
/content/drive/MyDrive/on-policy/StarCraftII/SMAC_Maps/2m_vs_1z.SC2Map
Process Process-3:
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 391, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 348, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 391, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 348, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 391, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 348, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 391, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 348, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
Traceback (most recent call last):
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 391, in reset
    self._launch()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/starcraft2/StarCraft2_Env.py", line 348, in _launch
    map_data=self._run_config.map_data(_map.path)),
  File "/usr/local/envs/marl/lib/python3.6/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'SMAC_Maps/2m_vs_1z.SC2Map' not found.
CloseHandler: 127.0.0.1:46288 disconnected
CloseHandler: 127.0.0.1:35620 disconnected
CloseHandler: 127.0.0.1:40056 disconnected
CloseHandler: 127.0.0.1:35666 disconnected
CloseHandler: 127.0.0.1:59260 disconnected
Traceback (most recent call last):
  File "../train/train_smac.py", line 262, in <module>
    main(sys.argv[1:])
  File "../train/train_smac.py", line 247, in main
    runner.run()
  File "/content/drive/MyDrive/on-policy/onpolicy/runner/shared/smac_runner.py", line 17, in run
    self.warmup()
  File "/content/drive/MyDrive/on-policy/onpolicy/runner/shared/smac_runner.py", line 100, in warmup
    obs, share_obs, available_actions = self.envs.reset()
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 377, in reset
    results = [remote.recv() for remote in self.remotes]
  File "/content/drive/MyDrive/on-policy/onpolicy/envs/env_wrappers.py", line 377, in <listcomp>
    results = [remote.recv() for remote in self.remotes]
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/envs/marl/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
